### ISSUE TITLE
Any way to get back the old layout for the popup?

### ISSUE THREAD

**Issue by sollniss** [versusvoid/rikaigu#3]
The new design looks terrible and make the popup huge. The layout being the same as the original rikaikun is what set this addon apart from yomichan with its even more terrible layout.

Just a checkbox to get the simple design, maybe?

**Comment by dethransam** [comment]
Yes please. I think the thick black bars between everything look really out of place. It was really nice the way it was

**Comment by versusvoid** [comment]
To get rid of them entirely - disable expression recognition (checkbox in options or press E while popup is visible).
Or propose better design which I will adopt.
